/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/auth/device-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Revoke this device token */
		delete: operations['auth_revoke'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/exchange': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Exchange magic token for device token */
		post: operations['auth_exchange'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register an account */
		post: operations['auth_register'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/request-link': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request a sign-in link */
		post: operations['auth_request_link'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The device owner's communities */
		get: operations['communities_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Upcoming events */
		get: operations['events_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Event details with my_rsvp */
		get: operations['events_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/rsvp': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Set my RSVP */
		put: operations['events_rsvp'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Visible groups of a community */
		get: operations['groups_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Group feed page (cursor-paginated) */
		get: operations['posts_index'];
		put?: never;
		/** Create a post */
		post: operations['posts_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/comments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Comment on a post */
		post: operations['comments_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/home': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Merged Home across communities */
		get: operations['home_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/instance': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Instance capabilities */
		get: operations['instance_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/openapi.json': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** This document */
		get: operations['openapi'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AuthExchangeResponse */
		AuthExchangeResponse: {
			device_token: string;
			user: components['schemas']['AuthUser'];
		};
		/** AuthRegisterResponse */
		AuthRegisterResponse: {
			/** @enum {string} */
			status: 'confirmation_sent';
			user: components['schemas']['AuthUser'];
		};
		/** AuthUser */
		AuthUser: {
			display_name: string | null;
			/** Format: email */
			email: string;
			/** Format: uuid */
			id: string;
		};
		/** Author */
		Author: {
			display_name: string;
			/** Format: uuid */
			id: string;
			/** @enum {string} */
			type: 'user' | 'group' | 'guest';
		} | null;
		/** Comment */
		Comment: {
			author?: components['schemas']['Author'];
			body_markdown?: string | null;
			deleted: boolean;
			/** Format: uuid */
			id: string;
			/** Format: date-time */
			inserted_at: string;
			/** Format: uuid */
			parent_comment_id?: string | null;
			/** @description Guest comments awaiting moderation — visible to moderators only */
			pending_approval: boolean;
		};
		/** Community */
		Community: {
			description?: string | null;
			/** Format: uuid */
			id: string;
			name: string;
			slug: string;
		};
		/**
		 * Error
		 * @description The one error envelope: stable code, human message.
		 */
		Error: {
			error: {
				/** @example not_found */
				code: string;
				details?: Record<string, never> | null;
				message: string;
			};
		};
		/** Event */
		Event: {
			all_day: boolean;
			description_markdown?: string | null;
			/** Format: date-time */
			ends_at?: string | null;
			/** Format: uuid */
			group_id: string;
			/** Format: uuid */
			id: string;
			location_name?: string | null;
			location_url?: string | null;
			/** @enum {string|null} */
			my_rsvp?: 'yes' | 'no' | 'maybe' | null;
			rsvp_counts: {
				maybe: number;
				no: number;
				yes: number;
			};
			/** @description Volunteer signup slots — present on event detail, empty on lists */
			slots?: {
				capacity: number;
				claimants?: components['schemas']['Author'][];
				/** Format: uuid */
				id: string;
				taken: number;
				title: string;
			}[];
			/** Format: date-time */
			starts_at: string;
			timezone: string;
			title: string;
		};
		/** Group */
		Group: {
			archived: boolean;
			description?: string | null;
			features: string[];
			/** Format: uuid */
			id: string;
			name: string;
			sealed: boolean;
			slug: string;
			/** @enum {string} */
			visibility: 'private' | 'community' | 'public_link' | 'public_listed';
		};
		/** HomeGroupSummary */
		HomeGroupSummary: {
			/** Format: uuid */
			id: string;
			name: string;
			slug: string;
		};
		/**
		 * HomeResponse
		 * @description Upcoming events and recent activity across all the device owner's communities
		 */
		HomeResponse: {
			recent_activity: (components['schemas']['Post'] & {
				community: components['schemas']['Community'];
				group: components['schemas']['HomeGroupSummary'];
			})[];
			upcoming_events: (components['schemas']['Event'] & {
				community: components['schemas']['Community'];
				group: components['schemas']['HomeGroupSummary'];
			})[];
		};
		/** Instance */
		Instance: {
			api_versions: string[];
			default_locale: string;
			features: {
				guest_rsvp: boolean;
				/** @enum {string} */
				registration: 'open' | 'web_only';
				web_push: boolean;
			};
			instance_name: string;
			version: string;
		};
		/** Poll */
		Poll: {
			anonymous: boolean;
			/** Format: date-time */
			closes_at?: string | null;
			/** Format: uuid */
			id: string;
			multiple_choice: boolean;
			options: {
				/** Format: uuid */
				id: string;
				text: string;
				votes: number;
			}[];
		} | null;
		/** Post */
		Post: {
			acknowledgment_required: boolean;
			author?: components['schemas']['Author'];
			body_markdown?: string | null;
			comment_count?: number | null;
			comments?: components['schemas']['Comment'][];
			deleted: boolean;
			/** Format: date-time */
			edited_at?: string | null;
			/** Format: uuid */
			group_id: string;
			/** Format: uuid */
			id: string;
			pinned: boolean;
			poll?: components['schemas']['Poll'];
			/** Format: date-time */
			published_at: string;
			/** @description Emoji → count */
			reactions?: {
				[key: string]: number;
			};
		};
		/** StatusResponse */
		StatusResponse: {
			status: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	auth_revoke: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Revoked */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_exchange: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					device_name?: string | null;
					magic_token?: string;
				};
			};
		};
		responses: {
			/** @description Device token and user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthExchangeResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					display_name?: string;
					/** Format: email */
					email?: string;
				};
			};
		};
		responses: {
			/** @description Registered — confirmation email sent */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthRegisterResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_request_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** Format: email */
					email?: string;
				};
			};
		};
		responses: {
			/** @description Always {status: sent} — no account enumeration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	communities_index: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Community'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_index: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Event'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Event'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_rsvp: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @enum {string} */
					status?: 'yes' | 'no' | 'maybe';
				};
			};
		};
		responses: {
			/** @description The recorded status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	groups_index: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Group'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_index: {
		parameters: {
			query?: {
				/** @description Opaque cursor from next_cursor */
				after?: string;
				/** @description 1..100, default 25 */
				limit?: string;
			};
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Post'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					acknowledgment_required?: string | null;
					body_markdown?: string;
					poll?: Record<string, never> | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Post'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	comments_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
					parent_comment_id?: string | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data?: components['schemas']['Comment'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	home_show: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Upcoming events and recent activity, labeled */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HomeResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	instance_show: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Instance metadata and feature discovery */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Instance'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	openapi: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The OpenAPI 3 document */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
}
