/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/communities': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The device owner's communities */
		get: operations['communities_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/passkey/challenge': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start a passkey sign-in (WebAuthn assertion options) */
		post: operations['auth_passkey_challenge'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/slots/{slot_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete a slot and its claims (creator/moderator) */
		delete: operations['events_delete_slot'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create an event, or a recurring series */
		post: operations['events_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Event details with my_rsvp */
		get: operations['events_show'];
		/** Edit this occurrence (creator/moderator) */
		put: operations['events_update'];
		post?: never;
		/** Delete an event (creator/moderator) */
		delete: operations['events_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/instance': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Instance capabilities */
		get: operations['instance_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/slots/{slot_id}/claim': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Claim a slot */
		put: operations['events_claim_slot'];
		post?: never;
		/** Release my claim on a slot */
		delete: operations['events_unclaim_slot'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/files/{file_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** A stored file's display bytes (inline images, downloads otherwise) */
		get: operations['files_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/comments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Comment on a post */
		post: operations['comments_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/{notification_id}/read': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Mark one notification read */
		put: operations['notifications_mark_read'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/rsvp': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Set my RSVP */
		put: operations['events_rsvp'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/reactions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Toggle my emoji reaction on a post */
		post: operations['posts_react'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/files/{file_id}/download': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** A stored file as a forced download */
		get: operations['files_download'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/comments/{comment_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Edit an event comment (author) */
		put: operations['events_update_comment'];
		post?: never;
		/** Delete an event comment — soft (author) or hard (moderator) */
		delete: operations['events_delete_comment'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/pin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Pin a post (moderator) */
		put: operations['posts_pin'];
		post?: never;
		/** Unpin a post (moderator) */
		delete: operations['posts_unpin'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/acknowledgments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Who has and hasn't acknowledged (author/admins) */
		get: operations['posts_acknowledgments'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/uploads': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upload a feed attachment (multipart) */
		post: operations['uploads_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/acknowledgment': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Acknowledge a post (idempotent) */
		put: operations['posts_acknowledge'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Visible groups of a community */
		get: operations['groups_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/slots': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add a signup slot (creator/moderator) */
		post: operations['events_create_slot'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/openapi.json': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** This document */
		get: operations['openapi'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Upcoming events */
		get: operations['events_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/files/{file_id}/thumbnail': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** An image's thumbnail (WebP) */
		get: operations['files_thumbnail'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/poll/votes': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Set my poll selection (empty list to unvote) */
		put: operations['poll_vote'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/comments/{comment_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Edit a comment's body (author) */
		put: operations['comments_update'];
		post?: never;
		/** Delete a comment — soft (author) or hard (moderator); answers the tombstone */
		delete: operations['comments_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/comments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Comment on an event */
		post: operations['events_create_comment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Edit a post's body (author) */
		put: operations['posts_update'];
		post?: never;
		/** Delete a post — soft/tombstone (author) or `?hard=true` (moderator) */
		delete: operations['posts_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The device owner's notifications (cursor-paginated, newest first) */
		get: operations['notifications_index'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/device-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Revoke this device token */
		delete: operations['auth_revoke'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Group feed page (cursor-paginated) */
		get: operations['posts_index'];
		put?: never;
		/** Create a post */
		post: operations['posts_create'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/request-link': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request a sign-in link */
		post: operations['auth_request_link'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/notifications/read-all': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Mark all notifications read */
		put: operations['notifications_mark_all_read'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register an account */
		post: operations['auth_register'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/passkey/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify a passkey assertion for a device token */
		post: operations['auth_passkey_verify'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/groups/{group_slug}/posts/{post_id}/comments/{comment_id}/reactions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Toggle my emoji reaction on a comment */
		post: operations['comments_react'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/comments/{comment_id}/reactions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Toggle my emoji reaction on an event comment */
		post: operations['events_react_comment'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/push-subscriptions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a Web Push subscription */
		post: operations['push_subscriptions_create'];
		/** Remove a Web Push subscription by endpoint */
		delete: operations['push_subscriptions_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/communities/{community_slug}/events/{event_id}/cancellation': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Cancel this occurrence (ADR 0019) */
		put: operations['events_cancel'];
		post?: never;
		/** Reinstate a cancelled occurrence */
		delete: operations['events_uncancel'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/home': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Merged Home across communities */
		get: operations['home_show'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/auth/exchange': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Exchange a magic token, or an emailed sign-in code, for a device token */
		post: operations['auth_exchange'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * Attachment
		 * @description A stored file attached to a post, in display order.
		 */
		Attachment: {
			byte_size: number;
			content_type: string;
			download_url: string;
			filename: string;
			height?: number | null;
			/** Format: uuid */
			id: string;
			/** @enum {string} */
			kind: 'image' | 'file';
			position: number;
			/** Format: uuid */
			stored_file_id: string;
			thumbnail_url?: string | null;
			url: string;
			width?: number | null;
		};
		/** AuthExchangeResponse */
		AuthExchangeResponse: {
			device_token: string;
			user: components['schemas']['AuthUser'];
		};
		/** AuthRegisterResponse */
		AuthRegisterResponse: {
			/** @enum {string} */
			status: 'confirmation_sent';
			user: components['schemas']['AuthUser'];
		};
		/** AuthUser */
		AuthUser: {
			display_name: string | null;
			/** Format: email */
			email: string;
			/** Format: uuid */
			id: string;
		};
		/** Author */
		Author: {
			display_name: string;
			/** Format: uuid */
			id: string;
			/** @enum {string} */
			type: 'user' | 'group' | 'guest';
		} | null;
		/** Comment */
		Comment: {
			author?: components['schemas']['Author'];
			body_markdown?: string | null;
			deleted: boolean;
			/** Format: date-time */
			edited_at?: string | null;
			/** Format: uuid */
			id: string;
			/** Format: date-time */
			inserted_at: string;
			/** @description Emoji the caller has reacted with */
			my_reactions: string[];
			/** Format: uuid */
			parent_comment_id?: string | null;
			/** @description Guest comments awaiting moderation — visible to moderators only */
			pending_approval: boolean;
			/** @description Emoji → count */
			reactions: {
				[key: string]: number;
			};
		};
		/** Community */
		Community: {
			description?: string | null;
			/** Format: uuid */
			id: string;
			name: string;
			slug: string;
		};
		/**
		 * Error
		 * @description The one error envelope: stable code, human message.
		 */
		Error: {
			error: {
				/** @example not_found */
				code: string;
				details?: Record<string, never> | null;
				message: string;
			};
		};
		/** Event */
		Event: {
			all_day: boolean;
			/** @description A cancelled occurrence stays viewable but leaves listings and feeds */
			cancelled: boolean;
			/** @description Present on event detail, empty on lists */
			comments: components['schemas']['Comment'][];
			comments_locked: boolean;
			description_markdown?: string | null;
			/** Format: date-time */
			ends_at?: string | null;
			/** @description The host group's summary, for provenance without a second fetch */
			group?: {
				/** Format: uuid */
				id: string;
				name: string;
				slug: string;
			} | null;
			/** Format: uuid */
			group_id: string;
			/** Format: uuid */
			id: string;
			location_name?: string | null;
			location_url?: string | null;
			/** @enum {string|null} */
			my_rsvp?: 'yes' | 'no' | 'maybe' | null;
			rsvp_counts: {
				maybe: number;
				no: number;
				yes: number;
			};
			/**
			 * Format: uuid
			 * @description Set when this event is one occurrence of a recurring series (ADR 0019)
			 */
			series_id?: string | null;
			/** @description Volunteer signup slots — present on event detail, empty on lists */
			slots: {
				capacity: number;
				claimants?: components['schemas']['Author'][];
				/** Format: uuid */
				id: string;
				taken: number;
				title: string;
			}[];
			/** Format: date-time */
			starts_at: string;
			timezone: string;
			title: string;
		};
		/**
		 * EventParams
		 * @description Create or edit an event. On create, an optional `recurrence` object materializes a series (ADR 0019) and the response is the first occurrence carrying its series_id. On edit, changes apply to this occurrence only.
		 */
		EventParams: {
			all_day?: boolean | null;
			description_markdown?: string | null;
			/** Format: date-time */
			ends_at?: string | null;
			location_name?: string | null;
			location_url?: string | null;
			/** @description Create only — turns the event into a bounded recurring series */
			recurrence?: {
				/** @enum {string} */
				frequency: 'weekly' | 'biweekly' | 'monthly';
				/**
				 * Format: date
				 * @description Last date the series may run
				 */
				until: string;
			} | null;
			/** Format: date-time */
			starts_at: string;
			timezone?: string | null;
			title: string;
		};
		/** Group */
		Group: {
			archived: boolean;
			description?: string | null;
			features: string[];
			/** Format: uuid */
			id: string;
			name: string;
			sealed: boolean;
			slug: string;
			/** @enum {string} */
			visibility: 'private' | 'community' | 'public_link' | 'public_listed';
		};
		/** HomeGroupSummary */
		HomeGroupSummary: {
			/** Format: uuid */
			id: string;
			name: string;
			slug: string;
		};
		/**
		 * HomeResponse
		 * @description Upcoming events and recent activity across all the device owner's communities
		 */
		HomeResponse: {
			recent_activity: (components['schemas']['Post'] & {
				community: components['schemas']['Community'];
				group: components['schemas']['HomeGroupSummary'];
			})[];
			upcoming_events: (components['schemas']['Event'] & {
				community: components['schemas']['Community'];
				group: components['schemas']['HomeGroupSummary'];
			})[];
		};
		/** Instance */
		Instance: {
			api_versions: string[];
			default_locale: string;
			features: {
				guest_rsvp: boolean;
				/** @enum {string} */
				registration: 'open' | 'web_only';
				web_push: boolean;
			};
			instance_name: string;
			version: string;
		};
		/**
		 * Notification
		 * @description An in-app notification. Navigate via community.slug + group.slug plus whichever of post_id/comment_id/event_id is set.
		 */
		Notification: {
			actor?: components['schemas']['Author'];
			/** Format: uuid */
			comment_id?: string | null;
			community?: components['schemas']['Community'];
			/** Format: uuid */
			event_id?: string | null;
			group?: {
				/** Format: uuid */
				id: string;
				name: string;
				slug: string;
			} | null;
			/** Format: uuid */
			id: string;
			/** Format: date-time */
			inserted_at: string;
			/** @enum {string} */
			kind:
				| 'post'
				| 'mention'
				| 'reply'
				| 'acknowledgment_required'
				| 'event_created'
				| 'event_reminder';
			/** Format: uuid */
			post_id?: string | null;
			read: boolean;
			/** Format: date-time */
			read_at?: string | null;
		};
		/**
		 * PasskeyChallengeResponse
		 * @description WebAuthn assertion options (ADR 0018, usernameless): feed `challenge` and `rp_id` to navigator.credentials.get, then send the assertion together with `challenge_token` (opaque, short-lived) to the verify operation.
		 */
		PasskeyChallengeResponse: {
			/** @description base64url, no padding */
			challenge: string;
			challenge_token: string;
			rp_id: string;
		};
		/** Poll */
		Poll: {
			anonymous: boolean;
			/** Format: date-time */
			closes_at?: string | null;
			/** Format: uuid */
			id: string;
			multiple_choice: boolean;
			/** @description Option ids the caller currently votes for */
			my_votes: string[];
			options: {
				/** Format: uuid */
				id: string;
				text: string;
				votes: number;
			}[];
		} | null;
		/**
		 * PollParams
		 * @description A poll to create with a post. The post body is the question; options keep the order they are sent in.
		 */
		PollParams: {
			anonymous?: boolean | null;
			/** Format: date-time */
			closes_at?: string | null;
			multiple_choice?: boolean | null;
			options: {
				text: string;
			}[];
		} | null;
		/** Post */
		Post: {
			acknowledged_count: number;
			acknowledgment_required: boolean;
			attachments: components['schemas']['Attachment'][];
			author?: components['schemas']['Author'];
			body_markdown?: string | null;
			comment_count?: number | null;
			comments?: components['schemas']['Comment'][];
			deleted: boolean;
			/** Format: date-time */
			edited_at?: string | null;
			/** Format: uuid */
			group_id: string;
			/** Format: uuid */
			id: string;
			/** @description Whether the caller has acknowledged this post */
			my_acknowledged: boolean;
			/** @description Emoji the caller has reacted with */
			my_reactions: string[];
			/** @description Awaiting moderation (approval-queue groups) — visible only to the author and moderators */
			pending_approval: boolean;
			pinned: boolean;
			poll?: components['schemas']['Poll'];
			/** Format: date-time */
			published_at: string;
			/** @description Emoji → count */
			reactions: {
				[key: string]: number;
			};
		};
		/** StatusResponse */
		StatusResponse: {
			status: string;
		};
		/**
		 * StoredFile
		 * @description An uploaded file. `id` is what create-post's `stored_file_ids` takes; the URLs are Bearer-authorized API routes.
		 */
		StoredFile: {
			byte_size: number;
			content_type: string;
			download_url: string;
			filename: string;
			height?: number | null;
			/** Format: uuid */
			id: string;
			/** @enum {string} */
			kind: 'image' | 'file';
			thumbnail_url?: string | null;
			url: string;
			width?: number | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	communities_index: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Community'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_passkey_challenge: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Assertion options; usernameless, no email asked for */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PasskeyChallengeResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_delete_slot: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				slot_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EventParams'];
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['EventParams'];
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	instance_show: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Instance metadata and feature discovery */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Instance'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_claim_slot: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				slot_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_unclaim_slot: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				slot_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	files_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				file_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The file — served with its own content type */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/octet-stream': string;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	comments_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
					parent_comment_id?: string | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	notifications_mark_read: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notification_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Marked read */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_rsvp: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @enum {string} */
					status?: 'yes' | 'no' | 'maybe';
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: {
							/** Format: uuid */
							event_id: string;
							/** @enum {string} */
							status: 'yes' | 'no' | 'maybe';
						};
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_react: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					emoji?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	files_download: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				file_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The file bytes as an attachment */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/octet-stream': string;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_update_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_delete_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_pin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_unpin: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_acknowledgments: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: {
							acknowledged: components['schemas']['Author'][];
							pending: components['schemas']['Author'][];
						};
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	uploads_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'multipart/form-data': {
					/** Format: binary */
					file?: string;
					/** @description Skip the group file space; auto-expires in 30 days */
					transient?: boolean | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['StoredFile'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			413: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_acknowledge: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	groups_index: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Group'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_create_slot: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					capacity?: number;
					title?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	openapi: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The OpenAPI 3 document */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': Record<string, never>;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_index: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	files_thumbnail: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				file_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The thumbnail bytes */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/octet-stream': string;
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	poll_vote: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @description The full selection: single-choice polls keep the first id, multiple-choice polls keep them all */
					option_ids?: string[];
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Poll'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	comments_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	comments_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_create_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
					parent_comment_id?: string | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					body_markdown?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_delete: {
		parameters: {
			query?: {
				/** @description true for a moderator hard delete */
				hard?: string;
			};
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	notifications_index: {
		parameters: {
			query?: {
				/** @description Opaque cursor from next_cursor */
				after?: string;
				/** @description 1..100, default 25 */
				limit?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Notification'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_revoke: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Revoked */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_index: {
		parameters: {
			query?: {
				/** @description Opaque cursor from next_cursor */
				after?: string;
				/** @description 1..100, default 25 */
				limit?: string;
			};
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'][];
						next_cursor?: string | null;
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	posts_create: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					acknowledgment_required?: boolean | null;
					body_markdown?: string;
					poll?: components['schemas']['PollParams'];
					/** @description Ids from the uploads endpoint, in display order — must be the caller's own uploads into this group */
					stored_file_ids?: string[] | null;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Post'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_request_link: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** Format: email */
					email?: string;
				};
			};
		};
		responses: {
			/** @description Always {status: sent} — no account enumeration */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	notifications_mark_all_read: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Marked read */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					display_name?: string;
					/** Format: email */
					email?: string;
				};
			};
		};
		responses: {
			/** @description Registered — confirmation email sent */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthRegisterResponse'];
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_passkey_verify: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @description base64url, no padding */
					authenticator_data?: string;
					/** @description Returned verbatim from the challenge operation */
					challenge_token?: string;
					/** @description base64url, no padding */
					client_data_json?: string;
					/** @description base64url, no padding */
					credential_id?: string;
					device_name?: string | null;
					/** @description base64url, no padding */
					signature?: string;
				};
			};
		};
		responses: {
			/** @description Device token and user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthExchangeResponse'];
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	comments_react: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				group_slug: string;
				post_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					emoji?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_react_comment: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
				comment_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					emoji?: string;
				};
			};
		};
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Comment'];
					};
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	push_subscriptions_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					endpoint?: string;
					keys?: {
						auth?: string;
						p256dh?: string;
					};
				};
			};
		};
		responses: {
			/** @description Subscribed (idempotent upsert) */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	push_subscriptions_delete: {
		parameters: {
			query?: {
				/** @description The subscription's endpoint URL */
				endpoint?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Deleted (idempotent) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StatusResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_cancel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	events_uncancel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				community_slug: string;
				event_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Data envelope */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						data: components['schemas']['Event'];
					};
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	home_show: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Upcoming events and recent activity, labeled */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HomeResponse'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
	auth_exchange: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': {
					/** @description The 8-character sign-in code from the email (case-insensitive) */
					code?: string | null;
					device_name?: string | null;
					/** Format: email */
					email?: string | null;
					/** @description The emailed magic-link token. Either this, or email + code. */
					magic_token?: string | null;
				};
			};
		};
		responses: {
			/** @description Device token and user */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AuthExchangeResponse'];
				};
			};
			/** @description Error envelope */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
			/** @description Error envelope */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Error'];
				};
			};
		};
	};
}
