defmodule KammerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :kammer

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_kammer_key",
    signing_salt: "XiuAfGZq",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :user_agent, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :user_agent, session: @session_options]]

  # Realtime for API clients (ADR 0014). No origin check for the same
  # reason /api gets CORS `*` (issue #150): auth is the device token in
  # the connect params, never a cookie, so a cross-origin page gains
  # nothing a same-origin one doesn't already have — and the Svelte PWA
  # and native apps connect from origins this server can't predict.
  socket "/api/socket", KammerWeb.Api.UserSocket,
    websocket: [check_origin: false],
    longpoll: false

  # The instance-served Svelte PWA (ADR 0024, issue #176): the release
  # bundles the built client into priv/static/app (see Dockerfile), and
  # this serves its real files — hashed assets, manifest, icons — under
  # the base path. Anything that isn't a real file (client-side routes
  # like /app/sign-in/{token}) falls through to the router's PwaController
  # catch-all, which answers with index.html. When the directory is
  # absent (plain `mix phx.server` without a client build) this plug
  # simply never matches — the controller then explains instead of 500ing.
  # Mounted before the "/" static plug on purpose: priv/static/app lives
  # inside priv/static, so the root plug would otherwise raise in dev
  # ("app" is deliberately not in static_paths — these files are the
  # client build's, not the LiveView-era statics). Flip note (#187): the
  # mount point comes from :pwa_base_path; see config/config.exs for what
  # the flip to "/" involves.
  plug Plug.Static,
    at: Application.compile_env!(:kammer, :pwa_base_path),
    from: {:kammer, "priv/static/app"},
    gzip: not code_reloading?

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :kammer,
    gzip: not code_reloading?,
    only: KammerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :kammer
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # CORS for /api only (issue #150). Endpoint-level on purpose: OPTIONS
  # preflights match no route, so a router-pipeline plug would 404
  # before setting any header.
  plug KammerWeb.Plugs.ApiCors

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug KammerWeb.Router
end
